services:
  backend:
    build:
      context: ./backend
    ports:
      - "8081:8081"
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:80"

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: orkestHubDB

volumes:
  mongo-data:
